### ISSUE TITLE
0.2.1 cannot hold sync

### ISSUE THREAD

**Issue by derp55555** [GetGoji/goji-blockchain#11]
0.2.1 is unstable and drops out of sync all the time

**Comment by rhernaus** [comment]
The timelords produce Signage Points (SPs). 64 SPs is called 1 sub-slot. Blockchain difficulty targets 32 blocks found per sub-slot. **The maximum blocks per sub-slot is 128**. Difficulty adjusts every 4608 blocks. The blockchain recently restarted and there is a lot of farmers connected. We need to give the blockchain some time to adjust difficulty.

**Comment by rhernaus** [comment]
Also the client says it is out of sync if it does not see a new block/height for some time. It is not really out of sync.
