### ISSUE TITLE
[BUG] Found a lot of blocks but they can't add to the network.

### ISSUE THREAD

**Issue by vanthoi** [GetGoji/goji-blockchain#13]
Debug Log: `Too many blocks added, not adding block` . Luckily it just added a block. The network is less stable. In the network, there is a certain node or Dev's that has sent a lot of blocks to the network without farming

**Comment by rhernaus** [comment]
The timelords produce Signage Points (SPs). 64 SPs is called 1 sub-slot. Blockchain difficulty targets 32 blocks found per sub-slot. **The maximum blocks per sub-slot is 128**. Difficulty adjusts every 4608 blocks. The blockchain recently restarted and there is a lot of farmers connected. We need to give the blockchain some time to adjust difficulty.
If you see that message then the sub-slot was already full when you made the block.

**Comment by vanthoi** [comment]
> The timelords produce Signage Points (SPs). 64 SPs is called 1 sub-slot. Blockchain difficulty targets 32 blocks found per sub-slot. **The maximum blocks per sub-slot is 128**. Difficulty adjusts every 4608 blocks. The blockchain recently restarted and there is a lot of farmers connected. We need to give the blockchain some time to adjust difficulty.
> If you see that message then the sub-slot was already full when you made the block.
One day I found a lot like this.
`2021-06-27T21:34:14.487 harvester goji.harvester.harvester: INFO     2 plots were eligible for farming 4f31b35b3c... Found 1 proofs. Time: 0.75383 s. Total 649 plots`
 But today only 7 blocks are actually accepted. It is not accurate compared to the current network.
