### ISSUE TITLE
[BUG] No windows version

### ISSUE THREAD

**Issue by Nok74** [GetGoji/goji-blockchain#2]
**Describe the bug**
A clear and concise description of what the bug is. (If what you are experiencing is NOT a bug but instead a support issue, please open a Discussion instead!)

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

- OS: [e.g. Linux]
- OS Version/Flavor: [e.g. CentOS 7.2]
- CPU: [e.g. Intel Xeon 8175M]

**Additional context**

**Comment by grayfallstown** [comment]
Windows version available and running properly.

**Comment by rhernaus** [comment]
https://github.com/GetGoji/goji-blockchain/releases
