### ISSUE TITLE
[BUG]Still can't connect, windows version

### ISSUE THREAD

**Issue by qiuqiu1104** [GetGoji/goji-blockchain#4]
![image](https://user-images.githubusercontent.com/85153786/123519998-15672900-d6e1-11eb-95f8-e8ca998fb516.png)

**Comment by D1M3um** [comment]
me too

**Comment by Hedonay** [comment]
same

**Comment by Seanthedogboy** [comment]
Same issue with the GUI (electron) MacOS DMG
hey, another Aussie checking out chia forks, G'day quiqui1104

**Comment by rhernaus** [comment]
https://github.com/GetGoji/goji-blockchain/releases/tag/0.2.1
